(2023-05-16 19:21:30,031), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:22:06,852), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:22:17,450), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:22:18,236), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:22:35,488), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:22:37,818), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:22:38,466), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:22:43,815), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:22:44,415), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:22:48,687), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:23:42,774), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:24:49,928), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:26:32,232), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:29:26,620), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:29:41,004), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:29:44,158), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:29:45,155), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:29:50,265), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:30:15,726), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:30:22,975), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:30:23,715), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:30:24,465), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:30:42,646), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:30:43,293), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:31:03,579), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:31:04,244), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:31:10,197), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:31:12,783), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:31:13,321), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:31:14,228), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:31:45,718), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:31:49,204), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:32:08,163), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:32:08,895), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:32:09,530), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:32:50,052), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:32:50,665), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:32:51,380), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:32:52,040), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:00,599), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:01,167), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:24,147), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:24,825), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:48,138), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:49,190), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:54,456), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:55,320), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:56,520), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:58,190), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:58,679), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:33:59,189), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:34:38,004), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:10,397), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:30,026), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:30,543), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:31,018), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:31,631), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:32,674), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:42,107), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:42,576), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:43,324), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:43,947), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:55,439), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:35:56,555), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:36:06,550), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:04,881), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:05,536), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:15,195), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:15,708), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:22,508), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:32,859), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:33,518), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:42,330), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:42,937), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:43,629), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:47,834), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:48,349), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:37:54,788), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:38:24,291), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:38:50,628), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:38:51,232), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:39:14,780), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:39:30,105), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:39:30,641), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:39:38,983), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:39:39,651), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:39:40,378), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:39:42,264), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:39:42,748), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:40:07,105), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:40:07,624), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:40:24,618), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:40:25,238), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:40:33,396), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:40:33,866), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:40:48,681), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:40:54,178), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:40:55,017), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:40:55,908), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:00,573), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:15,805), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:16,528), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:17,022), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:21,120), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:21,805), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:22,342), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:26,061), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:26,592), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:27,349), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:52,980), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:53,517), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:54,119), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:54,418), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:58,037), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:41:58,555), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:42:31,253), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:42:56,706), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:42:57,569), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:44:08,910), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:44:09,669), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:44:23,936), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:44:24,684), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:44:43,560), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:44:44,138), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:44:44,930), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:45:49,660), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:48:47,120), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:49:13,252), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:52:58,533), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:53:02,687), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:53:04,521), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:54:07,527), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:54:08,177), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:57:49,103), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:57:49,851), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:58:14,855), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:58:15,742), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:58:33,609), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:58:34,220), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:58:38,499), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 19:59:45,321), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:00:13,720), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:02:12,920), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:02:13,761), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:02:17,950), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:02:18,668), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:02:37,702), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:02:38,355), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:02:38,868), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:02:40,072), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:02:43,909), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:02:44,478), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:03:20,088), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:03:21,017), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:03:51,996), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:04:33,034), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:05:37,166), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:05:44,505), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:06:23,510), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:06:49,192), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:06:49,930), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:07:07,126), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:07:21,093), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:07:25,984), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:07:31,786), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:07:32,800), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:07:41,497), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:07:48,245), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:08:06,678), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:08:09,930), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:09:11,566), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:09:50,832), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:10:14,812), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:10:24,011), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:10:31,936), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:10:56,576), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:10:57,441), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:11:41,943), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:11:42,570), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:12:33,100), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:12:33,741), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:12:34,809), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:13:51,132), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:14:05,847), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:14:06,538), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:14:07,411), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:16:29,159), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:16:48,051), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:16:59,022), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:17:41,804), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:17:43,417), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:18:09,624), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:18:10,661), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:18:18,652), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:18:27,847), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:19:29,325), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:19:35,055), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:19:36,261), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:19:41,114), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:19:46,158), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:20:17,588), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:20:34,884), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:20:35,599), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:20:58,601), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:21:53,503), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:22:13,574), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:22:14,434), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:22:23,547), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:22:24,377), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:22:34,993), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:22:35,804), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:23:40,905), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:25:15,525), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:26:52,531), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:26:53,434), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:27:31,758), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:27:32,343), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:27:32,788), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:27:42,476), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:27:43,302), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:27:59,948), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:28:00,649), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:28:01,240), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:28:01,911), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:28:02,637), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:28:03,257), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:28:18,315), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:28:19,168), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:28:39,393), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:28:40,222), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:28:42,571), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:29:05,260), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:29:14,809), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:29:32,369), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:30:31,796), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:30:32,736), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:30:56,170), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:33:10,067), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:33:27,777), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:33:52,064), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:33:52,748), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:33:59,069), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:33:59,928), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:34:00,542), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:34:03,825), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:34:08,794), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:34:09,439), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:34:25,749), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:35:20,579), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:39:55,477), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:39:56,271), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:42:08,995), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:43:18,922), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:43:30,192), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:43:35,512), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:43:47,783), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:44:49,831), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:44:57,686), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:45:15,404), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:45:16,377), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:59:36,737), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 20:59:51,859), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:00:27,695), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:00:28,789), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:00:43,493), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:00:44,249), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:01:21,524), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:01:40,162), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:03:35,357), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:03:39,555), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:04:29,081), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:04:29,754), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:04:41,862), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:04:53,571), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:05:45,687), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:05:46,446), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:06:07,689), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:06:41,665), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:06:42,334), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:06:52,289), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:07:09,013), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:07:48,759), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:07:49,862), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:07:58,605), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:08:06,898), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:08:07,858), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:10:26,297), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:11:14,962), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:12:09,374), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:12:24,112), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:12:28,519), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:12:56,008), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:13:31,740), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:13:50,208), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:13:51,316), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:14:15,686), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:14:54,767), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:15:42,444), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:16:22,713), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:16:23,705), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:41:22,399), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:47:41,643), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:48:37,917), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:49:23,391), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:49:53,594), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:49:54,200), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:50:05,854), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:50:06,464), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:50:23,011), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:50:23,623), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:50:50,042), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:51:04,479), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:51:05,475), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:51:22,496), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:51:28,122), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:51:28,772), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:53:19,286), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:59:35,601), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:59:41,762), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:59:47,260), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 21:59:57,168), [WARNING], django.request, Bad Request: /login-customer/
(2023-05-16 22:03:22,626), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:03:24,980), [WARNING], django.request, Not Found: /admin
(2023-05-16 22:03:25,121), [WARNING], django.request, Not Found: /admin
(2023-05-16 22:03:43,309), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:04:08,521), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:04:26,789), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:07:40,478), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:07:43,378), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-16 22:08:00,054), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:08:45,772), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:17:41,454), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:17:42,459), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:17:50,585), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:21:10,846), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:21:26,270), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:21:39,463), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:21:43,915), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:21:50,608), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:22:21,470), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:22:57,764), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:24:29,938), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:24:36,156), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:25:36,541), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:25:53,621), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:27:11,465), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:27:18,127), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:27:23,517), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:28:03,755), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:28:05,775), [WARNING], django.request, Not Found: /admin
(2023-05-16 22:28:05,979), [WARNING], django.request, Not Found: /admin
(2023-05-16 22:28:27,298), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:28:45,073), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:29:04,142), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:30:05,935), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:30:30,525), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:30:38,897), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:30:59,850), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:32:22,975), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:32:40,280), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:33:00,775), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:33:16,144), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:33:32,844), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:36:46,043), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:37:05,108), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:37:18,002), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:37:43,159), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:38:11,145), [ERROR], django.request, Internal Server Error: /create-order/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shop\views.py", line 94, in create_order
    order.delete()
    ^^^^^
UnboundLocalError: cannot access local variable 'order' where it is not associated with a value
(2023-05-16 22:38:23,636), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:39:54,390), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:40:01,212), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:43:45,300), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:44:06,656), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:44:16,034), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:44:35,834), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:44:51,248), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:45:00,356), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:45:09,071), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:45:26,247), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:45:58,633), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:46:06,801), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:46:16,728), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:46:28,141), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:46:37,804), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:46:47,792), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:46:58,972), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:47:39,581), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:47:55,478), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:49:32,809), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:49:39,110), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:50:12,718), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:50:19,506), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:51:58,423), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:52:03,240), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:52:16,300), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:52:20,546), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:53:12,194), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:53:18,850), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:53:41,042), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:53:50,255), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:54:22,345), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:54:26,112), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:54:37,819), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:54:42,031), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:55:11,139), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:55:14,642), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:55:40,286), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:55:43,352), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:56:05,810), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:56:09,520), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:56:30,046), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:56:55,450), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:57:21,713), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:59:07,733), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:59:13,184), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 22:59:29,127), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 22:59:34,316), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:00:40,198), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:00:45,186), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:01:05,512), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:01:17,998), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:01:26,851), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:01:32,196), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:01:41,556), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:01:45,563), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:02:01,951), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:02:10,352), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:02:49,381), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:02:53,519), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:03:01,343), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:03:08,010), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:03:16,596), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:03:23,744), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:03:30,906), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:03:39,051), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:03:50,079), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:03:53,375), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:04:10,011), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:04:15,531), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-16 23:04:23,062), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:04:47,024), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:04:51,276), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:11:26,625), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:11:36,509), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:11:39,548), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:11:42,261), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:11:43,038), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:14:18,368), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:14:33,612), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:15:03,462), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:15:52,414), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:15:55,068), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:15:55,701), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:16:49,104), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:16:50,247), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:00,328), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:00,948), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:01,475), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:01,873), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:02,263), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:02,641), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:02,970), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:03,290), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:10,606), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:17:11,365), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:11,836), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:12,321), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:17:12,783), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:20:36,891), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:20:44,933), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:20:45,643), [WARNING], django.request, Bad Request: /create-order/
(2023-05-16 23:22:49,139), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:24:55,041), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:25:00,100), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:54:55,663), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:55:23,889), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:55:43,250), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:57:10,553), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:58:08,552), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-16 23:58:33,915), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:09:55,949), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:11:59,560), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:12:08,195), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:12:18,881), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:14:22,721), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:14:53,639), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:15:17,700), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:15:21,196), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:16:48,343), [WARNING], django.request, Unauthorized: /shopmanager/register-applicant/
(2023-05-17 00:16:48,628), [WARNING], django.request, Unauthorized: /shopmanager/register-applicant/
(2023-05-17 00:17:05,047), [ERROR], django.request, Internal Server Error: /shopmanager/register-applicant/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\views.py", line 96, in register_applicant
    register_application = Register_Application.objects.create(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 878, in save_base
    post_save.send(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\signals.py", line 12, in product_quantity_mail
    send_mails.new_registerApplication_mail(instance)
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\mail_api\send_mails.py", line 89, in new_registerApplication_mail
    link_url = 'http://127.0.0.1:8000' + reverse('shopmanager:shopmanager-new-registrations')
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'shopmanager-new-registrations' not found. 'shopmanager-new-registrations' is not a valid view function or pattern name.
(2023-05-17 00:17:13,732), [ERROR], django.request, Internal Server Error: /shopmanager/register-applicant/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\views.py", line 96, in register_applicant
    register_application = Register_Application.objects.create(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 878, in save_base
    post_save.send(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\signals.py", line 12, in product_quantity_mail
    send_mails.new_registerApplication_mail(instance)
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\mail_api\send_mails.py", line 89, in new_registerApplication_mail
    link_url = 'http://127.0.0.1:8000' + reverse('shopmanager:shopmanager-new-registrations')
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'shopmanager-new-registrations' not found. 'shopmanager-new-registrations' is not a valid view function or pattern name.
(2023-05-17 00:17:14,283), [ERROR], django.request, Internal Server Error: /shopmanager/register-applicant/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\views.py", line 96, in register_applicant
    register_application = Register_Application.objects.create(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 878, in save_base
    post_save.send(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\signals.py", line 12, in product_quantity_mail
    send_mails.new_registerApplication_mail(instance)
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\mail_api\send_mails.py", line 89, in new_registerApplication_mail
    link_url = 'http://127.0.0.1:8000' + reverse('shopmanager:shopmanager-new-registrations')
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'shopmanager-new-registrations' not found. 'shopmanager-new-registrations' is not a valid view function or pattern name.
(2023-05-17 00:17:23,918), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:17:33,239), [ERROR], django.request, Internal Server Error: /shopmanager/register-applicant/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\views.py", line 96, in register_applicant
    register_application = Register_Application.objects.create(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 878, in save_base
    post_save.send(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\signals.py", line 12, in product_quantity_mail
    send_mails.new_registerApplication_mail(instance)
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\mail_api\send_mails.py", line 89, in new_registerApplication_mail
    link_url = 'http://127.0.0.1:8000' + reverse('shopmanager:shopmanager-new-registrations')
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'shopmanager-new-registrations' not found. 'shopmanager-new-registrations' is not a valid view function or pattern name.
(2023-05-17 00:18:07,060), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:18:16,259), [ERROR], django.request, Internal Server Error: /shopmanager/register-applicant/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\views.py", line 96, in register_applicant
    register_application = Register_Application.objects.create(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 878, in save_base
    post_save.send(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\signals.py", line 12, in product_quantity_mail
    send_mails.new_registerApplication_mail(instance)
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\mail_api\send_mails.py", line 89, in new_registerApplication_mail
    link_url = 'http://127.0.0.1:8000' + reverse('shopmanager:shopmanager-new-registrations')
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'shopmanager-new-registrations' not found. 'shopmanager-new-registrations' is not a valid view function or pattern name.
(2023-05-17 00:18:46,395), [ERROR], django.request, Internal Server Error: /shopmanager/register-applicant/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\views.py", line 96, in register_applicant
    register_application = Register_Application.objects.create(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 878, in save_base
    post_save.send(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\signals.py", line 12, in product_quantity_mail
    send_mails.new_registerApplication_mail(instance)
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\mail_api\send_mails.py", line 89, in new_registerApplication_mail
    link_url = 'http://127.0.0.1:8000' + reverse('shopmanager:shopmanager-new-registrations')
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'shopmanager-new-registrations' not found. 'shopmanager-new-registrations' is not a valid view function or pattern name.
(2023-05-17 00:20:31,061), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:20:33,579), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:23:17,707), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:23:18,225), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:23:18,633), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:23:21,188), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:23:21,558), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:23:27,339), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:23:27,842), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:24:03,773), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:24:04,365), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:24:07,175), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:24:10,140), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:24:22,985), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:24:35,351), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:24:35,774), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:25:23,314), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:25:33,512), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:25:34,081), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:25:37,428), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:25:38,067), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:26:22,061), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:26:22,556), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:26:25,674), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:26:26,347), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:26:34,742), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:26:51,242), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:26:51,745), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:27:05,255), [WARNING], django.request, Not Found: /admin
(2023-05-17 00:27:05,580), [WARNING], django.request, Not Found: /admin
(2023-05-17 00:28:07,848), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:28:55,669), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:29:04,830), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:29:05,297), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:29:05,910), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:29:10,304), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:29:10,814), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:29:43,093), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:30:01,318), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:30:07,408), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:30:33,621), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:30:35,265), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:30:51,246), [WARNING], django.request, Bad Request: /create-order/
(2023-05-17 00:31:03,131), [WARNING], django.request, Bad Request: /create-order/
(2023-05-17 00:32:01,500), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:32:05,450), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:32:05,995), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:32:06,565), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:32:11,955), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:32:12,388), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:32:12,795), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:33:40,460), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:33:45,732), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:33:47,317), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:34:08,150), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:34:09,684), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:34:41,624), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:34:43,264), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:34:48,743), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:35:34,034), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:35:36,086), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:36:08,079), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:36:09,664), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:36:14,699), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:36:21,732), [WARNING], django.request, Bad Request: /create-order/
(2023-05-17 00:37:30,061), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:42:30,103), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:42:41,830), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:43:02,188), [WARNING], django.request, Bad Request: /create-order/
(2023-05-17 00:45:22,245), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:45:23,455), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:45:42,849), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:45:44,662), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 00:45:58,284), [WARNING], django.request, Bad Request: /create-order/
(2023-05-17 00:47:24,179), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:47:28,666), [WARNING], django.request, Bad Request: /create-order/
(2023-05-17 00:47:42,130), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:47:47,991), [WARNING], django.request, Bad Request: /create-order/
(2023-05-17 00:48:01,284), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 00:48:07,378), [WARNING], django.request, Bad Request: /create-order/
(2023-05-17 01:15:05,305), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:19:12,778), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:19:34,678), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:19:45,058), [WARNING], django.request, Not Found: /admin
(2023-05-17 01:19:45,167), [WARNING], django.request, Not Found: /admin
(2023-05-17 01:27:05,311), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:27:39,331), [ERROR], django.request, Internal Server Error: /shopmanager/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1027, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'crispy_forms_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\views.py", line 34, in shopmanager_home
    return render(request, 'shopmanager/shopmanager_home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1089, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1029, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'crispy_forms_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
(2023-05-17 01:27:39,606), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:28:30,696), [ERROR], django.request, Internal Server Error: /shopmanager/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\views.py", line 34, in shopmanager_home
    return render(request, 'shopmanager/shopmanager_home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 115, in as_crispy_field
    template_path = "%s/field.html" % template_pack
                    ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\crispy_forms\utils.py", line 16, in get_template_pack
    return getattr(settings, "CRISPY_TEMPLATE_PACK")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\conf\__init__.py", line 94, in __getattr__
    val = getattr(_wrapped, name)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Settings' object has no attribute 'CRISPY_TEMPLATE_PACK'
(2023-05-17 01:28:31,021), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:29:05,895), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:29:13,644), [ERROR], django.request, Internal Server Error: /shopmanager/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\views.py", line 34, in shopmanager_home
    return render(request, 'shopmanager/shopmanager_home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Empty variable tag on line 80
(2023-05-17 01:29:13,818), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:29:16,535), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:36:02,422), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:39:02,718), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:42:28,425), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:42:30,395), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:45:06,978), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:45:07,585), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:45:08,595), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:45:49,222), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:45:50,052), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:46:04,311), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:46:04,886), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:46:05,900), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:46:30,213), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:46:30,787), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:46:41,996), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:46:42,565), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:46:43,597), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:46:47,141), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:47:21,578), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:47:23,144), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:47:34,860), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:50:04,275), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:50:04,820), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:50:25,412), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:50:53,799), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:50:54,333), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:50:54,834), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:50:58,857), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:50:59,356), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:51:03,201), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:51:03,777), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:54:26,102), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:54:35,576), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:54:42,476), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:54:42,992), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:54:51,774), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:54:59,018), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:54:59,595), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:55:00,133), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:55:33,261), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:55:33,854), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:55:39,477), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:55:40,040), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:55:44,072), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:55:44,792), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:55:49,107), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:55:49,833), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:55:55,572), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:55:56,093), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:56:12,678), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:56:32,833), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:57:42,426), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:57:43,268), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:57:51,195), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:57:51,813), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:58:25,084), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:58:25,632), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:58:26,247), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:58:39,521), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 01:58:40,336), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:00:00,363), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:00:05,711), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:00:06,220), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:00:34,425), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:00:34,987), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:00:35,691), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:01:11,644), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:01:12,239), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:01:39,105), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:02:14,720), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:02:35,442), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:02:36,491), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:02:59,294), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:02:59,786), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:00,218), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:00,554), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:00,731), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:03,201), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:03,800), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:12,460), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:12,947), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:13,372), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:20,842), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:21,350), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:21,994), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:25,029), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:25,815), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:32,427), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:33,090), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:55,381), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:03:56,064), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:04:24,823), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:04:25,311), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:04:25,835), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:04:26,211), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:04:30,859), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:04:31,414), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:04:31,924), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:04:38,274), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:04:38,886), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:05:03,844), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:05:04,483), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:05:12,334), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:05:12,849), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:05:13,351), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:05:14,059), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:05:21,835), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:05:22,344), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:05:22,839), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:06:18,151), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:06:19,157), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:06:26,794), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:06:49,895), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:06:50,435), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:06:50,931), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:06:54,498), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:07:21,950), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:07:47,788), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:07:48,510), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:07:48,944), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:07:53,463), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:07:54,049), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:08:10,150), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:08:10,707), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:08:11,246), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:08:17,733), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:08:18,268), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:09:21,809), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:09:22,470), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:02,044), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:02,927), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:13,269), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:13,812), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:14,522), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:18,302), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:19,455), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:26,576), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:27,149), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:31,040), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:31,560), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:32,062), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:32,662), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:33,115), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:44,408), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:44,881), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:45,194), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:10:50,524), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:01,365), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:16,154), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:16,688), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:17,463), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:30,264), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:30,766), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:31,292), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:35,609), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:40,602), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:41,253), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:45,838), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:46,306), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:46,831), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:48,291), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:52,584), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:53,053), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:11:53,743), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:00,293), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:00,748), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:10,943), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:11,446), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:11,926), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:12,387), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:26,130), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:26,649), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:27,244), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:52,299), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:52,793), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:53,417), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:56,521), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:12:58,287), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:16:13,824), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:20:11,524), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:20:58,123), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:20:58,691), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:21:05,300), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:21:05,979), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:21:16,894), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:21:28,943), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:21:30,063), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:21:33,789), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:21:34,280), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:25:43,248), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:27:09,515), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:27:30,008), [WARNING], django.request, Not Found: /admin
(2023-05-17 02:27:30,141), [WARNING], django.request, Not Found: /admin
(2023-05-17 02:28:16,526), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:30:28,269), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:32:28,816), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:33:33,218), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:33:34,372), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 02:43:45,289), [ERROR], django.request, Internal Server Error: /shopmanager/export-orders-as-pdf/3/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\views.py", line 74, in rendered_content
    self.resolve_template(self.template_name),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Empty variable tag on line 93
(2023-05-17 02:48:03,917), [ERROR], django.request, Internal Server Error: /shopmanager/export-orders-as-pdf/3/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column shop_order.subtotal_price does not exist
LINE 1: ...er"."user_profile_id", "shop_order"."order_date", "shop_orde...
                                                             ^
HINT:  Perhaps you meant to reference the column "shop_order.total_price".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\Desktop\Websites\Svenska_Svampar_website\svenska_svampar\shopmanager\views.py", line 74, in export_orders_as_pdf
    order = Order.objects.prefetch_related('orderitem_set').filter(user_profile__id=pk).first()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1046, in first
    for obj in (self if self.ordered else self.order_by("pk"))[:1]:
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 394, in __iter__
    self._fetch_all()
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column shop_order.subtotal_price does not exist
LINE 1: ...er"."user_profile_id", "shop_order"."order_date", "shop_orde...
                                                             ^
HINT:  Perhaps you meant to reference the column "shop_order.total_price".

(2023-05-17 02:51:02,852), [WARNING], django.request, Bad Request: /check-product-quantity/
(2023-05-17 02:51:24,084), [WARNING], django.request, Bad Request: /create-order/
(2023-05-17 03:02:30,301), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 03:02:52,225), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 03:03:05,158), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 03:03:15,460), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:19:15,927), [ERROR], django.security.DisallowedHost, Invalid HTTP_HOST header: '192.168.0.104:8000'. You may need to add '192.168.0.104' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.104:8000'. You may need to add '192.168.0.104' to ALLOWED_HOSTS.
(2023-05-17 17:19:16,102), [WARNING], django.request, Bad Request: /
(2023-05-17 17:19:16,204), [ERROR], django.security.DisallowedHost, Invalid HTTP_HOST header: '192.168.0.104:8000'. You may need to add '192.168.0.104' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.104:8000'. You may need to add '192.168.0.104' to ALLOWED_HOSTS.
(2023-05-17 17:19:16,239), [WARNING], django.request, Bad Request: /favicon.ico
(2023-05-17 17:19:51,430), [WARNING], django.request, Bad Request: /login-customer/
(2023-05-17 17:20:30,505), [WARNING], django.request, Bad Request: /create-order/
(2023-05-17 17:21:37,896), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:23:55,224), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:24:39,605), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:24:54,423), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:25:45,054), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:26:07,189), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:26:13,552), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:26:26,850), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:26:31,363), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:26:58,941), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:27:07,968), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:27:57,115), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:28:11,109), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:28:26,604), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:28:31,818), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:28:39,568), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:29:22,346), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:29:44,432), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:30:16,351), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:31:22,041), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:31:50,520), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:32:04,235), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:33:54,463), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:34:06,054), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:34:13,982), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:34:42,458), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:35:02,421), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:35:24,442), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:37:44,429), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:39:17,479), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:39:33,146), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:39:49,204), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:39:58,838), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:40:06,788), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:40:12,035), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:40:31,643), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:40:44,839), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:40:58,810), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:41:05,753), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 17:41:13,057), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:29:02,037), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:31:11,755), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:31:37,997), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:31:45,229), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:31:57,211), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:32:25,223), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:32:30,510), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:32:31,324), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:32:52,244), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:33:11,178), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:33:37,421), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:34:26,237), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:34:43,463), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:35:33,019), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:35:46,949), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:36:06,166), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:36:20,791), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:36:43,129), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:37:16,544), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:37:28,962), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:38:34,456), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:39:01,218), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:39:07,646), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:39:25,642), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:39:57,348), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:40:23,640), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:41:45,433), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:41:55,053), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:42:22,184), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:42:52,956), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:43:04,055), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:44:32,401), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:45:09,138), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:46:54,205), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:47:03,830), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:47:04,346), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:47:35,951), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:48:44,360), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:48:57,942), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:49:01,389), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:49:35,464), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:49:43,508), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:50:00,483), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:51:05,071), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:53:17,335), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:53:21,792), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:53:24,810), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:53:35,486), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:53:49,018), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:53:56,058), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:54:13,950), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:54:40,145), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:55:23,184), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:55:56,997), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:56:09,629), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:56:20,932), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:56:30,884), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:56:45,369), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:56:52,442), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:56:58,531), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:57:06,268), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:57:30,360), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:57:40,986), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:57:52,254), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:57:56,813), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:58:23,076), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:58:31,862), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:58:48,352), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:58:53,614), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:59:03,362), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:59:06,777), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:59:21,126), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 18:59:33,385), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:00:49,586), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:09:07,555), [ERROR], django.security.DisallowedHost, Invalid HTTP_HOST header: '192.168.0.104:8000'. You may need to add '192.168.0.104' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.104:8000'. You may need to add '192.168.0.104' to ALLOWED_HOSTS.
(2023-05-17 19:09:07,597), [WARNING], django.request, Bad Request: /shopmanager/
(2023-05-17 19:11:01,415), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:11:20,442), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:11:45,119), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:11:54,656), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:12:14,171), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:12:36,002), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:13:10,302), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:13:13,251), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:13:25,135), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:13:29,783), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:13:32,034), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:13:46,815), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:14:01,745), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:14:04,630), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:14:27,998), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:14:35,921), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:14:45,270), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:14:50,952), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:15:04,790), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:15:15,142), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:15:54,314), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:16:36,045), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:16:42,003), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:16:51,239), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:16:57,135), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:17:07,186), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:17:21,369), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:17:29,324), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:18:09,282), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:18:34,844), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:21:32,834), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:21:33,829), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:21:34,687), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:21:41,394), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:21:47,449), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:22:32,639), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:22:57,620), [WARNING], django.request, Not Found: /robots.txt
(2023-05-17 19:23:36,941), [WARNING], django.request, Not Found: /robots.txt
(2023-05-17 19:24:26,925), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:24:27,427), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:24:34,245), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:24:43,147), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:24:43,726), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:24:44,567), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:24:51,096), [WARNING], django.request, Not Found: /robots.txt
(2023-05-17 19:25:10,056), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-17 19:25:10,646), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 01:53:16,116), [ERROR], django.security.DisallowedHost, Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
(2023-05-21 01:53:16,271), [WARNING], django.request, Bad Request: /
(2023-05-21 01:53:16,521), [ERROR], django.security.DisallowedHost, Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
(2023-05-21 01:53:16,559), [WARNING], django.request, Bad Request: /favicon.ico
(2023-05-21 01:53:31,196), [ERROR], django.request, Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: shop_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\OneDrive\Desktop\website\shop\views.py", line 37, in shop_home
    for product in products:
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: shop_product
(2023-05-21 01:53:31,341), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 01:56:09,023), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 01:56:09,646), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 01:56:12,860), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 01:56:56,074), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 01:58:59,086), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 01:59:07,612), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 01:59:28,381), [WARNING], django.request, Not Found: /media/products/thumbnails/2023/05/21/640px-1-Up_Mushroom_Artwork_-_Super_Mario_3D_World.png
(2023-05-21 01:59:37,549), [WARNING], django.request, Not Found: /media/products/thumbnails/2023/05/21/640px-1-Up_Mushroom_Artwork_-_Super_Mario_3D_World.png
(2023-05-21 01:59:59,333), [WARNING], django.request, Not Found: /media/products/thumbnails/2023/05/21/640px-1-Up_Mushroom_Artwork_-_Super_Mario_3D_World.png
(2023-05-21 02:00:30,407), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:04:15,637), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:04:16,300), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:04:16,863), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:04:17,374), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:07:23,969), [ERROR], django.request, Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'math_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\OneDrive\Desktop\website\shop\views.py", line 44, in shop_home
    return render(request, 'shop/shop_home.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'math_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
l10n
log
static
tz
(2023-05-21 02:07:24,174), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:07:46,018), [ERROR], django.request, Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'math_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\OneDrive\Desktop\website\shop\views.py", line 44, in shop_home
    return render(request, 'shop/shop_home.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'math_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
l10n
log
static
tz
(2023-05-21 02:07:46,178), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:07:46,571), [ERROR], django.request, Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'math_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\OneDrive\Desktop\website\shop\views.py", line 44, in shop_home
    return render(request, 'shop/shop_home.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'math_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
l10n
log
static
tz
(2023-05-21 02:07:46,725), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:08:44,980), [ERROR], django.request, Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'math_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\OneDrive\Desktop\website\shop\views.py", line 44, in shop_home
    return render(request, 'shop/shop_home.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'math_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
l10n
log
static
tz
(2023-05-21 02:08:45,142), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:09:46,498), [ERROR], django.request, Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\OneDrive\Desktop\website\shop\views.py", line 44, in shop_home
    return render(request, 'shop/shop_home.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
(2023-05-21 02:09:46,670), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:10:01,174), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:10:01,872), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:10:45,758), [ERROR], django.request, Internal Server Error: /shopmanager/export-orders-as-pdf/1/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\views.py", line 73, in rendered_content
    return render_pdf_from_template(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 232, in render_pdf_from_template
    return convert_to_pdf(filename=input_file.filename,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 165, in convert_to_pdf
    return wkhtmltopdf(pages=pages, **cmd_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 146, in wkhtmltopdf
    return check_output(ck_args, **ck_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
(2023-05-21 02:11:12,107), [ERROR], django.request, Internal Server Error: /shopmanager/export-orders-as-pdf/1/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\views.py", line 73, in rendered_content
    return render_pdf_from_template(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 232, in render_pdf_from_template
    return convert_to_pdf(filename=input_file.filename,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 165, in convert_to_pdf
    return wkhtmltopdf(pages=pages, **cmd_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 146, in wkhtmltopdf
    return check_output(ck_args, **ck_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
(2023-05-21 02:11:17,060), [ERROR], django.request, Internal Server Error: /shopmanager/export-orders-as-pdf/1/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\views.py", line 73, in rendered_content
    return render_pdf_from_template(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 232, in render_pdf_from_template
    return convert_to_pdf(filename=input_file.filename,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 165, in convert_to_pdf
    return wkhtmltopdf(pages=pages, **cmd_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 146, in wkhtmltopdf
    return check_output(ck_args, **ck_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
(2023-05-21 02:11:17,205), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:11:17,605), [ERROR], django.request, Internal Server Error: /shopmanager/export-orders-as-pdf/1/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\views.py", line 73, in rendered_content
    return render_pdf_from_template(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 232, in render_pdf_from_template
    return convert_to_pdf(filename=input_file.filename,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 165, in convert_to_pdf
    return wkhtmltopdf(pages=pages, **cmd_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 146, in wkhtmltopdf
    return check_output(ck_args, **ck_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
(2023-05-21 02:11:17,752), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:11:18,004), [ERROR], django.request, Internal Server Error: /shopmanager/export-orders-as-pdf/1/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\views.py", line 73, in rendered_content
    return render_pdf_from_template(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 232, in render_pdf_from_template
    return convert_to_pdf(filename=input_file.filename,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 165, in convert_to_pdf
    return wkhtmltopdf(pages=pages, **cmd_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\wkhtmltopdf\utils.py", line 146, in wkhtmltopdf
    return check_output(ck_args, **ck_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
(2023-05-21 02:11:18,120), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:31:46,913), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 02:39:39,724), [ERROR], django.request, Internal Server Error: /create-order/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\OneDrive\Desktop\website\shop\views.py", line 99, in create_order
    order = Order.objects.create(user=user, user_profile = user_profile)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 892, in save_base
    post_save.send(
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\OneDrive\Desktop\website\shop\signals.py", line 22, in new_order_mailing
    mail_status = send_mails.new_order_mail(instance, pdf_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 39, in new_order_mail
    attachment = MessageAttachment(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ElasticEmail\model_utils.py", line 49, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MessageAttachment.__init__() missing 2 required positional arguments: 'binary_content' and 'name'
(2023-05-21 18:55:56,190), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 18:57:13,919), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 18:57:28,416), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 18:57:35,684), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 18:57:43,560), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 18:58:06,359), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 18:58:13,336), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 18:58:25,300), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 18:59:47,973), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 18:59:59,108), [ERROR], shopmanager, Error sending email for order 10 - Business name - 21/05/2023 16:59:55 HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 43, in new_order_mail
    response = sg.send(message)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
(2023-05-21 18:59:59,108), [ERROR], shopmanager, Error sending email for order 10 - Business name - 21/05/2023 16:59:55 HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 43, in new_order_mail
    response = sg.send(message)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
(2023-05-21 19:00:56,352), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 19:01:00,930), [ERROR], shopmanager, Error sending email for order 11 - Business name - 21/05/2023 17:00:58 HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 43, in new_order_mail
    response = sg.send(message)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
(2023-05-21 19:01:00,930), [ERROR], shopmanager, Error sending email for order 11 - Business name - 21/05/2023 17:00:58 HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 43, in new_order_mail
    response = sg.send(message)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
(2023-05-21 19:01:09,598), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 19:09:22,904), [ERROR], django.request, Internal Server Error: /create-order/
Traceback (most recent call last):
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\OneDrive\Desktop\website\shop\views.py", line 100, in create_order
    send_mails.insufficient_stock_mail(user_profile, email_insufficient_stock_items)
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 122, in insufficient_stock_mail
    html_content += f'<p><strong>{item["name"]}</strong> - x{item["quantity"]}, but we have only {item["stock_left"]} on stock</p><br>'
                                                                                                  ~~~~^^^^^^^^^^^^^^
KeyError: 'stock_left'
(2023-05-21 19:09:30,306), [ERROR], shopmanager, Error sending email for insufficient stock - 1 - Business name - 20/05/2023 23:57:35 HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 135, in insufficient_stock_mail
    response = sg.send(message)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
(2023-05-21 19:09:30,306), [ERROR], shopmanager, Error sending email for insufficient stock - 1 - Business name - 20/05/2023 23:57:35 HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 135, in insufficient_stock_mail
    response = sg.send(message)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
(2023-05-21 19:09:30,309), [WARNING], django.request, Bad Request: /create-order/
(2023-05-21 19:11:40,276), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 19:11:44,078), [ERROR], shopmanager, Error sending email for insufficient stock - 1 - Business name - 20/05/2023 23:57:35 HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 135, in insufficient_stock_mail
    response = sg.send(message)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
(2023-05-21 19:11:44,078), [ERROR], shopmanager, Error sending email for insufficient stock - 1 - Business name - 20/05/2023 23:57:35 HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 135, in insufficient_stock_mail
    response = sg.send(message)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
(2023-05-21 19:11:44,080), [WARNING], django.request, Bad Request: /create-order/
(2023-05-21 19:11:56,913), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 19:12:00,955), [ERROR], shopmanager, Error sending email for insufficient stock - 1 - Business name - 20/05/2023 23:57:35 HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 135, in insufficient_stock_mail
    response = sg.send(message)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
(2023-05-21 19:12:00,955), [ERROR], shopmanager, Error sending email for insufficient stock - 1 - Business name - 20/05/2023 23:57:35 HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Users\bedzo\OneDrive\Desktop\website\shopmanager\mail_api\send_mails.py", line 135, in insufficient_stock_mail
    response = sg.send(message)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "C:\Users\bedzo\AppData\Local\Programs\Python\Python311\Lib\site-packages\python_http_client\client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
(2023-05-21 19:12:00,960), [WARNING], django.request, Bad Request: /create-order/
(2023-05-21 19:12:19,150), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-21 19:46:48,615), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 21:34:10,880), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 21:35:39,550), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 21:35:40,239), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:01:48,183), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:11,263), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:17,748), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:18,280), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:18,765), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:19,362), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:28,804), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:29,291), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:29,771), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:30,659), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:36,532), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:36,980), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:37,493), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:51,417), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:51,827), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:04:52,224), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:05:02,316), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:05:02,719), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:05:06,137), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:10:02,867), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:13:54,271), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:14:35,262), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:14:47,155), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:15:25,135), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:15:30,344), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:17:07,074), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:18:41,427), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:18:50,927), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:19:20,498), [WARNING], django.request, Not Found: /favicon.ico
(2023-05-22 22:20:02,833), [WARNING], django.request, Not Found: /favicon.ico
